// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: IMCESP32UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Image4;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
lv_obj_t * ui_ScreenHome;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_buttonOuputVacula;
lv_obj_t * ui_Image2;
lv_obj_t * ui_labelResultWeight;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Container3;
lv_obj_t * ui_RollerTipoVisitante;
lv_obj_t * ui_labelTipoVisitante;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Roller2;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Image6;
void ui_event_buttonSetting(lv_event_t * e);
lv_obj_t * ui_buttonSetting;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Container6;
lv_obj_t * ui_tagIMG;
lv_obj_t * ui_imc;
lv_obj_t * ui_resultIMC;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Label4;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
lv_obj_t * ui_ScreenSettings;
void ui_event_Image7(lv_event_t * e);
lv_obj_t * ui_Image7;
lv_obj_t * ui_Label8;
void ui_event_Container7(lv_event_t * e);
lv_obj_t * ui_Container7;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Label9;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Label10;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Image12;
// CUSTOM VARIABLES


// SCREEN: ui_ScreenWifiSettings
void ui_ScreenWifiSettings_screen_init(void);
lv_obj_t * ui_ScreenWifiSettings;
lv_obj_t * ui_Container14;
void ui_event_Image14(lv_event_t * e);
lv_obj_t * ui_Image14;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Container15;
lv_obj_t * ui_Image13;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Container16;
lv_obj_t * ui_Image16;
lv_obj_t * ui_Image15;
lv_obj_t * ui_Label14;
lv_obj_t * ui_containerSSID;
void ui_event_rowSSID(lv_event_t * e);
lv_obj_t * ui_rowSSID;
lv_obj_t * ui_Container25;
lv_obj_t * ui_Image23;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Image24;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_1579410345[1] = {&ui_img_1311752867};
const lv_image_dsc_t * ui_imgset_860380543[1] = {&ui_img_696145193};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_FADE_ON, 500, 2000, &ui_ScreenHome_screen_init);
        _ui_screen_delete(&ui_Screen1);
    }
}

void ui_event_buttonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_OVER_LEFT, 500, 0, &ui_ScreenSettings_screen_init);
        _ui_screen_delete(&ui_ScreenHome);
    }
}

void ui_event_Image7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenHome, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenHome_screen_init);
        _ui_screen_delete(&ui_ScreenSettings);
    }
}

void ui_event_Container7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ScreenWifiSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScreenWifiSettings_screen_init);
        _ui_screen_delete(&ui_ScreenSettings);
    }
}

void ui_event_Image14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_ScreenSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScreenSettings_screen_init);
        _ui_screen_delete(&ui_ScreenWifiSettings);
    }
}

void ui_event_rowSSID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        toWifiPassword(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_ScreenHome_screen_init();
    ui_ScreenSettings_screen_init();
    ui_ScreenWifiSettings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
