// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPIMC_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_splashScreen
void ui_splashScreen_screen_init(void);
void ui_event_splashScreen(lv_event_t * e);
lv_obj_t * ui_splashScreen;
lv_obj_t * ui_Image2;
lv_obj_t * ui_spinnerSplash;
lv_obj_t * ui_derechosDeAutorLabel;
// CUSTOM VARIABLES


// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
lv_obj_t * ui_homeScreen;
lv_obj_t * ui_internetUnavailableImg;
lv_obj_t * ui_stateChargeBateryBar;
lv_obj_t * ui_containerdkdkdd;
lv_obj_t * ui_Dropdown3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_containerRollerAge;
lv_obj_t * ui_Dropdown2;
lv_obj_t * ui_Label2;
lv_obj_t * ui_containerResultIMC;
lv_obj_t * ui_labelHeader;
lv_obj_t * ui_labelResultIMC;
lv_obj_t * ui_labelDescriptionIMC;
lv_obj_t * ui_Image1;
lv_obj_t * ui_containerHeight;
lv_obj_t * ui_imgHeight;
lv_obj_t * ui_labelHeight;
lv_obj_t * ui_labelTypeUnits;
lv_obj_t * ui_containerWeight;
lv_obj_t * ui_labelWeight;
lv_obj_t * ui_imgWeight;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_image_dsc_t * ui_imgset_1579410345[1] = {&ui_img_1311752867};
const lv_image_dsc_t * ui_imgset_860380543[1] = {&ui_img_696145193};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_splashScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_homeScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 1000, &ui_homeScreen_screen_init);
        _ui_screen_delete(&ui_splashScreen);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_splashScreen_screen_init();
    ui_homeScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_splashScreen);
}
