// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPIMC_UI

#ifndef _ESPIMC_UI_UI_H
#define _ESPIMC_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_splashScreen
void ui_splashScreen_screen_init(void);
void ui_event_splashScreen(lv_event_t * e);
extern lv_obj_t * ui_splashScreen;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_spinnerSplash;
extern lv_obj_t * ui_derechosDeAutorLabel;
// CUSTOM VARIABLES

// SCREEN: ui_homeScreen
void ui_homeScreen_screen_init(void);
extern lv_obj_t * ui_homeScreen;
extern lv_obj_t * ui_internetUnavailableImg;
extern lv_obj_t * ui_stateChargeBateryBar;
extern lv_obj_t * ui_containerdkdkdd;
extern lv_obj_t * ui_Dropdown3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_containerRollerAge;
extern lv_obj_t * ui_Dropdown2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_containerResultIMC;
extern lv_obj_t * ui_labelHeader;
extern lv_obj_t * ui_labelResultIMC;
extern lv_obj_t * ui_labelDescriptionIMC;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_containerHeight;
extern lv_obj_t * ui_imgHeight;
extern lv_obj_t * ui_labelHeight;
extern lv_obj_t * ui_labelTypeUnits;
extern lv_obj_t * ui_containerWeight;
extern lv_obj_t * ui_labelWeight;
extern lv_obj_t * ui_imgWeight;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_will_png);    // assets/logo_will.png
LV_IMG_DECLARE(ui_img_unavailable_wifi_png);    // assets/unavailable_wifi.png
LV_IMG_DECLARE(ui_img_available_wifi_png);    // assets/available_wifi.png
LV_IMG_DECLARE(ui_img_1311752867);    // assets/mdi--human-male-height 1.png
LV_IMG_DECLARE(ui_img_696145193);    // assets/mdi--weight-kilogram 1.png
LV_IMG_DECLARE(ui_img_save_png);    // assets/save.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
