// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: IMCESP32UI

#ifndef _IMCESP32UI_UI_H
#define _IMCESP32UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenHome
void ui_ScreenHome_screen_init(void);
extern lv_obj_t * ui_ScreenHome;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_buttonOuputVacula;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_labelResultWeight;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_RollerTipoVisitante;
extern lv_obj_t * ui_labelTipoVisitante;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image6;
void ui_event_buttonSetting(lv_event_t * e);
extern lv_obj_t * ui_buttonSetting;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_tagIMG;
extern lv_obj_t * ui_imc;
extern lv_obj_t * ui_resultIMC;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
extern lv_obj_t * ui_ScreenSettings;
void ui_event_Image7(lv_event_t * e);
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label8;
void ui_event_Container7(lv_event_t * e);
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Image12;
// CUSTOM VARIABLES

// SCREEN: ui_ScreenWifiSettings
void ui_ScreenWifiSettings_screen_init(void);
extern lv_obj_t * ui_ScreenWifiSettings;
extern lv_obj_t * ui_Container14;
void ui_event_Image14(lv_event_t * e);
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_containerSSID;
void ui_event_rowSSID(lv_event_t * e);
extern lv_obj_t * ui_rowSSID;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image24;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_logo_will_png);    // assets/logo_will.png
LV_IMG_DECLARE(ui_img_unavailable_wifi_png);    // assets/unavailable_wifi.png
LV_IMG_DECLARE(ui_img_696145193);    // assets/mdi--weight-kilogram 1.png
LV_IMG_DECLARE(ui_img_1311752867);    // assets/mdi--human-male-height 1.png
LV_IMG_DECLARE(ui_img_save_png);    // assets/save.png
LV_IMG_DECLARE(ui_img_cogico_png);    // assets/cogIco.png
LV_IMG_DECLARE(ui_img_home_png);    // assets/home.png
LV_IMG_DECLARE(ui_img_available_wifi_png);    // assets/available_wifi.png
LV_IMG_DECLARE(ui_img_309409143);    // assets/arrow-right.png
LV_IMG_DECLARE(ui_img_googlesheetsicon_png);    // assets/googleSheetsIcon.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png
LV_IMG_DECLARE(ui_img_lock_png);    // assets/lock.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
