// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: IMCESP32UI

#include "ui.h"

#if LV_USE_KEYBOARD && LV_BUILD_EXAMPLES

static void event_cb(lv_event_t * e){
	lv_obj_t * btn = lv_event_get_target(e);
	lv_obj_t * label = lv_obj_get_child(btn, 0);
	LV_UNUSED(label);
	LV_LOG_USER("BUTTON %s clicked", lv_label_get_text(label));
}


void toWifiPassword(lv_event_t * e)
{

	lv_obj_t * mbox1 = lv_msgbox_create(NULL);

	lv_msgbox_add_title(mbox1, "Wifi Password");
	
	
	lv_msgbox_add_text(mbox1, "This is a message box with two buttons.");
	lv_msgbox_add_close_button(mbox1);


	lv_obj_t * textarea = lv_textarea_create(mbox1);
	lv_obj_align(textarea, LV_ALIGN_CENTER, 0, 20);
	
	lv_obj_t * btn;
	btn = lv_msgbox_add_footer_button(mbox1, "Apply");
	lv_obj_add_event_cb(btn, event_cb, LV_EVENT_CLICKED, NULL);
	btn = lv_msgbox_add_footer_button(mbox1, "Cancel");
	lv_obj_add_event_cb(btn, event_cb, LV_EVENT_CLICKED, NULL);
	return;

	
}

#endif