// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: IMCESP32UI

#include "ui.h"

void ui_ScreenWifiSettings_screen_init(void)
{
    ui_ScreenWifiSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenWifiSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container14 = lv_obj_create(ui_ScreenWifiSettings);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 120);
    lv_obj_set_height(ui_Container14, 58);
    lv_obj_set_x(ui_Container14, -96);
    lv_obj_set_y(ui_Container14, -205);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Container14);
    lv_image_set_src(ui_Image14, &ui_img_available_wifi_png);
    lv_obj_set_width(ui_Image14, 30);
    lv_obj_set_height(ui_Image14, 30);
    lv_obj_set_x(ui_Image14, -126);
    lv_obj_set_y(ui_Image14, -141);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image14, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Image14, lv_color_hex(0x3039B1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -75);
    lv_obj_set_y(ui_Label13, -141);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Wi-Fi");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_ScreenWifiSettings);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_height(ui_Container13, 50);
    lv_obj_set_width(ui_Container13, lv_pct(90));
    lv_obj_set_x(ui_Container13, 0);
    lv_obj_set_y(ui_Container13, -136);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container13, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container13);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 232);
    lv_obj_set_height(ui_Container15, 50);
    lv_obj_set_x(ui_Container15, -32);
    lv_obj_set_y(ui_Container15, 19);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Container15);
    lv_image_set_src(ui_Image13, &ui_img_check_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "CLARO_3FEWEF");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label12, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Container13);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, 69);
    lv_obj_set_height(ui_Container16, 50);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_image_create(ui_Container16);
    lv_image_set_src(ui_Image16, &ui_img_lock_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Container16);
    lv_image_set_src(ui_Image15, &ui_img_available_wifi_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_ScreenWifiSettings);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -80);
    lv_obj_set_y(ui_Label14, -51);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "OTRAS REDES");

    ui_containerSSID = lv_obj_create(ui_ScreenWifiSettings);
    lv_obj_remove_style_all(ui_containerSSID);
    lv_obj_set_height(ui_containerSSID, 259);
    lv_obj_set_width(ui_containerSSID, lv_pct(100));
    lv_obj_set_x(ui_containerSSID, 0);
    lv_obj_set_y(ui_containerSSID, 108);
    lv_obj_set_align(ui_containerSSID, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_containerSSID, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_containerSSID, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_containerSSID, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rowSSID = lv_obj_create(ui_containerSSID);
    lv_obj_remove_style_all(ui_rowSSID);
    lv_obj_set_height(ui_rowSSID, 68);
    lv_obj_set_width(ui_rowSSID, lv_pct(87));
    lv_obj_set_x(ui_rowSSID, -9);
    lv_obj_set_y(ui_rowSSID, -18);
    lv_obj_set_align(ui_rowSSID, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowSSID, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rowSSID, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rowSSID, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_rowSSID, lv_color_hex(0x363636), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rowSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rowSSID, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rowSSID, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container25 = lv_obj_create(ui_rowSSID);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_width(ui_Container25, 242);
    lv_obj_set_height(ui_Container25, 58);
    lv_obj_set_x(ui_Container25, -86);
    lv_obj_set_y(ui_Container25, -68);
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container25, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container25, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_image_create(ui_Container25);
    lv_image_set_src(ui_Image23, &ui_img_available_wifi_png);
    lv_obj_set_width(ui_Image23, 30);
    lv_obj_set_height(ui_Image23, 30);
    lv_obj_set_x(ui_Image23, -126);
    lv_obj_set_y(ui_Image23, -141);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Container25);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -75);
    lv_obj_set_y(ui_Label18, -141);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "SSID");
    lv_obj_set_style_pad_left(ui_Label18, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label18, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image24 = lv_image_create(ui_rowSSID);
    lv_image_set_src(ui_Image24, &ui_img_lock_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image24, 125);
    lv_obj_set_y(ui_Image24, -131);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Image14, ui_event_Image14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rowSSID, ui_event_rowSSID, LV_EVENT_ALL, NULL);

}
