// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPIMC_UI

#include "ui.h"

void ui_splashScreen_screen_init(void)
{
    ui_splashScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_splashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_splashScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_splashScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_Image2 = lv_image_create(ui_splashScreen);
    lv_image_set_src(ui_Image2, &ui_img_logo_will_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 293
    lv_obj_set_x(ui_Image2, -3);
    lv_obj_set_y(ui_Image2, -11);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spinnerSplash = lv_spinner_create(ui_splashScreen);
    //lv_spinner_set_anim_params(ui_spinnerSplash, 1000, 90);
    lv_obj_set_width(ui_spinnerSplash, 80);
    lv_obj_set_height(ui_spinnerSplash, 80);
    lv_obj_set_align(ui_spinnerSplash, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spinnerSplash, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_spinnerSplash, lv_color_hex(0x00DA00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_spinnerSplash, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_derechosDeAutorLabel = lv_label_create(ui_splashScreen);
    lv_obj_set_width(ui_derechosDeAutorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_derechosDeAutorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_derechosDeAutorLabel, 21);
    lv_obj_set_y(ui_derechosDeAutorLabel, -227);
    lv_obj_set_align(ui_derechosDeAutorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_derechosDeAutorLabel, "creado por Manases Rivas 3DSA 2024");
    lv_obj_add_flag(ui_derechosDeAutorLabel, LV_OBJ_FLAG_FLOATING);     /// Flags

    lv_obj_add_event_cb(ui_splashScreen, ui_event_splashScreen, LV_EVENT_ALL, NULL);

}
