// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: IMCESP32UI

#include "ui.h"

void ui_ScreenHome_screen_init(void)
{
    ui_ScreenHome = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 178);
    lv_obj_set_height(ui_Container1, 32);
    lv_obj_set_x(ui_Container1, 67);
    lv_obj_set_y(ui_Container1, -220);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 175);
    lv_obj_set_y(ui_Label1, -354);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SIN INTERNET");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Container1);
    lv_image_set_src(ui_Image1, &ui_img_unavailable_wifi_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image1, 134);
    lv_obj_set_y(ui_Image1, -211);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container2 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_height(ui_Container2, 239);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, -77);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_AROUND);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonOuputVacula = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_buttonOuputVacula, 141);
    lv_obj_set_height(ui_buttonOuputVacula, 64);
    lv_obj_set_x(ui_buttonOuputVacula, -71);
    lv_obj_set_y(ui_buttonOuputVacula, -114);
    lv_obj_set_align(ui_buttonOuputVacula, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_buttonOuputVacula, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_buttonOuputVacula, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonOuputVacula, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonOuputVacula, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonOuputVacula, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonOuputVacula, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_buttonOuputVacula);
    lv_image_set_src(ui_Image2, &ui_img_696145193);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image2, -31);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelResultWeight = lv_label_create(ui_buttonOuputVacula);
    lv_obj_set_width(ui_labelResultWeight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelResultWeight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelResultWeight, 15);
    lv_obj_set_y(ui_labelResultWeight, -1);
    lv_obj_set_align(ui_labelResultWeight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelResultWeight, "0 KG");
    lv_obj_set_style_text_font(ui_labelResultWeight, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_Button3, 149);
    lv_obj_set_height(ui_Button3, 64);
    lv_obj_set_x(ui_Button3, -46);
    lv_obj_set_y(ui_Button3, -25);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Button3);
    lv_image_set_src(ui_Image3, &ui_img_1311752867);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -78);
    lv_obj_set_y(ui_Label3, -25);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "0 CM");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 210);
    lv_obj_set_height(ui_Container3, 154);
    lv_obj_set_x(ui_Container3, -31);
    lv_obj_set_y(ui_Container3, 107);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerTipoVisitante = lv_roller_create(ui_Container3);
    lv_roller_set_options(ui_RollerTipoVisitante,
                          "ninguno\nRepresentante legal\nDocente INFRAVENZ\nEstudiante INFRAVENZ\nDocente particular\nEstudiante particular\nPersona particular\nEspecialista evaluador\n",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerTipoVisitante, 199);
    lv_obj_set_height(ui_RollerTipoVisitante, 100);
    lv_obj_set_x(ui_RollerTipoVisitante, -10);
    lv_obj_set_y(ui_RollerTipoVisitante, 157);
    lv_obj_set_align(ui_RollerTipoVisitante, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RollerTipoVisitante, lv_color_hex(0x313C43), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTipoVisitante, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerTipoVisitante, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTipoVisitante, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTipoVisitante, lv_color_hex(0x04DB00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTipoVisitante, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_labelTipoVisitante = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_labelTipoVisitante, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelTipoVisitante, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelTipoVisitante, -45);
    lv_obj_set_y(ui_labelTipoVisitante, -2);
    lv_obj_set_align(ui_labelTipoVisitante, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTipoVisitante, "Tipo de visitante");

    ui_Container4 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 80);
    lv_obj_set_height(ui_Container4, 151);
    lv_obj_set_x(ui_Container4, 96);
    lv_obj_set_y(ui_Container4, 132);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0x272E30), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller2 = lv_roller_create(ui_Container4);
    lv_roller_set_options(ui_Roller2, "ning", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller2, 53);
    lv_obj_set_height(ui_Roller2, 100);
    lv_obj_set_x(ui_Roller2, -64);
    lv_obj_set_y(ui_Roller2, 104);
    lv_obj_set_align(ui_Roller2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x313C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_Roller2, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x00DA00), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller2, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 102);
    lv_obj_set_y(ui_Label6, 3);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Edad");

    ui_Container5 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 201);
    lv_obj_set_height(ui_Container5, 84);
    lv_obj_set_x(ui_Container5, -1);
    lv_obj_set_y(ui_Container5, 185);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Container5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_Button2, 68);
    lv_obj_set_height(ui_Button2, 58);
    lv_obj_set_x(ui_Button2, 36);
    lv_obj_set_y(ui_Button2, 154);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button2, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x313C41), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x29434B), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_Image6 = lv_image_create(ui_Button2);
    lv_image_set_src(ui_Image6, &ui_img_save_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image6, 3);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonSetting = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_buttonSetting, 68);
    lv_obj_set_height(ui_buttonSetting, 58);
    lv_obj_set_x(ui_buttonSetting, -57);
    lv_obj_set_y(ui_buttonSetting, 154);
    lv_obj_set_align(ui_buttonSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonSetting, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_buttonSetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonSetting, lv_color_hex(0x4A484A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_buttonSetting);
    lv_image_set_src(ui_Image5, &ui_img_cogico_png);
    lv_obj_set_width(ui_Image5, 50);
    lv_obj_set_height(ui_Image5, 50);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_ScreenHome);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_height(ui_Container6, 79);
    lv_obj_set_width(ui_Container6, lv_pct(92));
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 88);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0x202C31), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tagIMG = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_tagIMG, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tagIMG, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tagIMG, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tagIMG, "IMC");
    lv_obj_set_style_text_color(ui_tagIMG, lv_color_hex(0x15FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tagIMG, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tagIMG, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imc = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_imc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_imc, "0");

    ui_resultIMC = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_resultIMC, 245);
    lv_obj_set_height(ui_resultIMC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_resultIMC, -114);
    lv_obj_set_y(ui_resultIMC, 82);
    lv_obj_set_align(ui_resultIMC, LV_ALIGN_CENTER);
    lv_label_set_text(ui_resultIMC, "Sin datos que analizar");
    lv_obj_set_style_text_align(ui_resultIMC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_ScreenHome);
    lv_image_set_src(ui_Image8, &ui_img_home_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image8, -137);
    lv_obj_set_y(ui_Image8, -221);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_ScreenHome);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -87);
    lv_obj_set_y(ui_Label4, -218);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "INICIO");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonSetting, ui_event_buttonSetting, LV_EVENT_ALL, NULL);

}
