// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: ESPIMC_UI

#include "ui.h"

static void call_event_Button2(lv_event_t * e){

    lv_obj_t * obj = lv_event_get_target(e);
    lv_obj_t * menu = lv_event_get_user_data(e);
    
    if(lv_menu_back_button_is_root(menu, obj)){
        ui_event_Button2(e);
    }
    
}

static void show_message_box(lv_event_t * e){
    lv_event_code_t SSID = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_target(e);


    message_box = lv_msgbox_create(ui_settingScreen);
    lv_obj_set_size(message_box, lv_pct(100), lv_pct(100));
    lv_msgbox_add_title(message_box, lv_list_get_button_text(list_SSID, obj));
    lv_msgbox_add_close_button(message_box);
    


    ui_textareaPasswordWifi = lv_textarea_create(message_box);
    lv_obj_set_width(ui_textareaPasswordWifi, lv_pct(100));
    lv_obj_set_height(ui_textareaPasswordWifi, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_align(ui_textareaPasswordWifi, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_textareaPasswordWifi, 60);
    lv_textarea_set_placeholder_text(ui_textareaPasswordWifi, "clave ...");
    lv_textarea_set_one_line(ui_textareaPasswordWifi, true);

    ui_Keyboard1 = lv_keyboard_create(ui_settingScreen);
    lv_obj_set_height(ui_Keyboard1, 152);
    lv_obj_set_width(ui_Keyboard1, lv_pct(100));
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 163);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_keyboard_set_textarea(ui_Keyboard1, ui_textareaPasswordWifi);
    lv_obj_add_event_cb(ui_textareaPasswordWifi, ui_event_textareaPasswordWifi, LV_EVENT_ALL, NULL);

}

void ui_settingScreen_screen_init(void)
{


    ui_settingScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_settingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_obj_t * menu;


    lv_obj_t * root_page;
    lv_obj_t * cont;
    lv_obj_t * label_cont;
    
    
    menu = lv_menu_create(ui_settingScreen);
    lv_obj_set_style_bg_color(menu, lv_color_hex(0x101418), 0); // color de fondo
    lv_menu_set_mode_root_back_button(menu, LV_MENU_ROOT_BACK_BUTTON_ENABLED); // boton de regreso
    lv_obj_add_event_cb(menu, call_event_Button2, LV_EVENT_RELEASED, menu); // se asigna el evento de regreso al boton de regreso al menu
    lv_obj_t * back_root_button = lv_menu_get_main_header_back_button(menu);
    lv_obj_set_size(back_root_button, 30, 30);
    lv_obj_set_flex_flow(back_root_button, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(back_root_button, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_size(menu,lv_display_get_horizontal_resolution(NULL), lv_display_get_vertical_resolution(NULL)); // darle dimenciones al alto y ancho de el menu
    lv_obj_center(menu); // alinear el menu al centro
    

    lv_obj_t * wifi_page;
    lv_obj_t * section;
    lv_obj_t * contentWIfiConected;

    
    wifi_page = lv_menu_page_create(menu, "WI-FI");
    lv_obj_set_style_pad_hor(wifi_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(wifi_page);
    
    contentWIfiConected = lv_obj_create(section);
    lv_obj_set_width(contentWIfiConected, lv_pct(100));
    lv_obj_set_height(contentWIfiConected, 40);
    lv_obj_set_align(contentWIfiConected, LV_ALIGN_CENTER);
    lv_obj_remove_flag(contentWIfiConected, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    lv_obj_t * img_check_wifi = lv_img_create(contentWIfiConected);
    lv_image_set_src(img_check_wifi, &ui_img_check_png);
    lv_obj_set_width(img_check_wifi, LV_SIZE_CONTENT);
    lv_obj_set_height(img_check_wifi, LV_SIZE_CONTENT);
    lv_obj_set_x(img_check_wifi, -120);
    lv_obj_set_y(img_check_wifi, 0);
    lv_image_set_scale(img_check_wifi, 150);
    lv_obj_set_align(img_check_wifi, LV_ALIGN_CENTER);


    ui_Spinner1 = lv_spinner_create(contentWIfiConected);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 30);
    lv_obj_set_height(ui_Spinner1, 30);
    lv_obj_set_x(ui_Spinner1, -116);
    lv_obj_set_y(ui_Spinner1, -80);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_arc_width(ui_Spinner1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);



    lv_obj_t * label = lv_label_create(contentWIfiConected);
    lv_label_set_text(label, "CLARO37_DF382");
    lv_obj_set_x(label, -27);
    lv_obj_set_y(label, 0);
    lv_obj_set_align(label, LV_ALIGN_CENTER);



    
    


    lv_obj_t * img_lock_wifi = lv_image_create(contentWIfiConected);
    lv_obj_set_x(img_lock_wifi, 88);
    lv_obj_set_y(img_lock_wifi, 0);
    lv_img_set_src(img_lock_wifi, &ui_img_lock_png);
    lv_image_set_scale(img_lock_wifi, 150);
    lv_obj_set_align(img_lock_wifi, LV_ALIGN_CENTER);


    lv_obj_t * img_available_wifi = lv_image_create(contentWIfiConected);
    lv_obj_set_x(img_available_wifi, 122);
    lv_obj_set_y(img_available_wifi, 0);
    lv_image_set_src(img_available_wifi, LV_SYMBOL_WIFI);
    lv_obj_set_align(img_available_wifi, LV_ALIGN_CENTER);


    cont = lv_menu_cont_create(wifi_page);
    lv_obj_set_style_pad_top(cont, 40, 0);
    label = lv_label_create(cont);
    lv_label_set_text(label, "OTRAS REDES");

    section = lv_menu_section_create(wifi_page);
    list_SSID = lv_list_create(section);
    lv_obj_set_width(list_SSID, lv_pct(100));
    // lv_list_add_text(list_SSID, "claro1234"); 
    lv_obj_t * btn;
    btn = lv_list_add_button(list_SSID, LV_SYMBOL_WIFI, "claro1234");
    lv_obj_add_event_cb(btn, show_message_box, LV_EVENT_RELEASED, NULL);
    btn = lv_list_add_button(list_SSID, LV_SYMBOL_WIFI, "tigo232");
    lv_obj_add_event_cb(btn, show_message_box, LV_EVENT_RELEASED, NULL);
    btn = lv_list_add_button(list_SSID, LV_SYMBOL_WIFI, "san mighel");
    lv_obj_add_event_cb(btn, show_message_box, LV_EVENT_RELEASED, NULL);
    btn = lv_list_add_button(list_SSID, LV_SYMBOL_WIFI, "iphone");
    lv_obj_add_event_cb(btn, show_message_box, LV_EVENT_RELEASED, NULL);
    
    

    // programacion de la pagina root




    root_page = lv_menu_page_create(menu, "CONFIGURACION");
    lv_obj_set_style_pad_hor(root_page, lv_obj_get_style_pad_left(lv_menu_get_main_header(menu), 0), 0);
    section = lv_menu_section_create(root_page);

    cont = lv_menu_cont_create(section);
    lv_obj_t * imgConfWifi = lv_image_create(cont);
    lv_image_set_src(imgConfWifi, LV_SYMBOL_WIFI);
    label_cont = lv_label_create(cont);
    lv_label_set_text(label_cont, "WI-FI");
    lv_menu_set_load_page_event(menu, cont, wifi_page);

    
    lv_menu_set_sidebar_page(menu, NULL);
    lv_menu_clear_history(menu);
    lv_menu_set_page(menu, root_page);

    
    // fin
    

 



    // ui_Button2 = lv_button_create(ui_settingScreen);
    // lv_obj_set_width(ui_Button2, 100);
    // lv_obj_set_height(ui_Button2, 50);
    // lv_obj_set_x(ui_Button2, -98);
    // lv_obj_set_y(ui_Button2, -203);
    // lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    // lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // ui_Image3 = lv_image_create(ui_Button2);
    // lv_image_set_src(ui_Image3, &ui_img_image_back_png);
    // lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 35
    // lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 35
    // lv_obj_set_x(ui_Image3, -25);
    // lv_obj_set_y(ui_Image3, -2);
    // lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    // lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    // lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    // lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}
